# Generated by Django 4.0.1 on 2022-01-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN', 'OPEN'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('NEW', 'NEW'), ('OPEN DEAL', 'OPEN DEAL'), ('CONNECTED', 'CONNECTED'), ('IN PROGRESS', 'IN PROGRESS'), ('BAD TIMING', 'BAD TIMING ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('TWITTER', 'TWITTER'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('REFERRAL', 'REFERRAL'), ('INSTAGRAM', 'INSTAGRAM')], max_length=100),
        ),
    ]
