# Generated by Django 4.0.1 on 2022-01-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('BAD TIMING', 'BAD TIMING '), ('CONNECTED', 'CONNECTED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN DEAL', 'OPEN DEAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('REFERRAL', 'REFERRAL')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact_rep',
            name='organization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
