# Generated by Django 4.0.1 on 2022-01-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_lead_status_alter_lead_source_of_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('BAD TIMING', 'BAD TIMING '), ('IN PROGRESS', 'IN PROGRESS'), ('CONNECTED', 'CONNECTED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN DEAL', 'OPEN DEAL'), ('NEW', 'NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'INSTAGRAM'), ('REFERRAL', 'REFERRAL'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('TWITTER', 'TWITTER')], max_length=100),
        ),
    ]
