# Generated by Django 4.0.1 on 2022-01-16 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('BAD TIMING', 'BAD TIMING '), ('OPEN DEAL', 'OPEN DEAL'), ('IN PROGRESS', 'IN PROGRESS'), ('UNQUALIFIED', 'UNQUALIFIED'), ('NEW', 'NEW'), ('CONNECTED', 'CONNECTED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('TWITTER', 'TWITTER'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('REFERRAL', 'REFERRAL'), ('INSTAGRAM', 'INSTAGRAM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
