# Generated by Django 4.0.1 on 2022-01-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_user_is_admin_user_is_contact_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.contact_rep'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('BAD TIMING', 'BAD TIMING '), ('NEW', 'NEW'), ('CONNECTED', 'CONNECTED'), ('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN DEAL', 'OPEN DEAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('INSTAGRAM', 'INSTAGRAM'), ('REFERRAL', 'REFERRAL'), ('TWITTER', 'TWITTER')], max_length=100),
        ),
    ]
