# Generated by Django 4.0.1 on 2022-01-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_contact_rep_alter_lead_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('IN PROGRESS', 'IN PROGRESS'), ('OPEN DEAL', 'OPEN DEAL'), ('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN', 'OPEN'), ('BAD TIMING', 'BAD TIMING '), ('NEW', 'NEW'), ('CONNECTED', 'CONNECTED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('REFERRAL', 'REFERRAL'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM')], max_length=100),
        ),
    ]
