# Generated by Django 4.0.1 on 2022-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_organization_alter_lead_lead_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('CONNECTED', 'CONNECTED'), ('IN PROGRESS', 'IN PROGRESS'), ('NEW', 'NEW'), ('UNQUALIFIED', 'UNQUALIFIED'), ('OPEN', 'OPEN'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('OPEN DEAL', 'OPEN DEAL'), ('BAD TIMING', 'BAD TIMING ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('REFERRAL', 'REFERRAL'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER')], max_length=100),
        ),
    ]
