# Generated by Django 4.0.1 on 2022-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_lead_status_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('UNQUALIFIED', 'UNQUALIFIED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('CONNECTED', 'CONNECTED'), ('NEW', 'NEW'), ('OPEN', 'OPEN'), ('OPEN DEAL', 'OPEN DEAL'), ('BAD TIMING', 'BAD TIMING '), ('IN PROGRESS', 'IN PROGRESS')], max_length=100),
        ),
    ]
