# Generated by Django 4.0.1 on 2022-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('OPEN DEAL', 'OPEN DEAL'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('UNQUALIFIED', 'UNQUALIFIED'), ('CONNECTED', 'CONNECTED'), ('NEW', 'NEW'), ('BAD TIMING', 'BAD TIMING ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('REFERRAL', 'REFERRAL')], max_length=100),
        ),
    ]
