# Generated by Django 4.0.1 on 2022-01-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('BAD TIMING', 'BAD TIMING '), ('CONNECTED', 'CONNECTED'), ('OPEN', 'OPEN'), ('UNQUALIFIED', 'UNQUALIFIED'), ('NEW', 'NEW'), ('OPEN DEAL', 'OPEN DEAL'), ('IN PROGRESS', 'IN PROGRESS'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('REFERRAL', 'REFERRAL'), ('GOOGLE SEARCH', 'GOOGLE SEARCH')], max_length=100),
        ),
    ]
