# Generated by Django 4.0.1 on 2022-01-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_lead_status_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_contacted',
            field=models.CharField(default='01-31-2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('UNQUALIFIED', 'UNQUALIFIED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('CONNECTED', 'CONNECTED'), ('OPEN DEAL', 'OPEN DEAL'), ('BAD TIMING', 'BAD TIMING '), ('IN PROGRESS', 'IN PROGRESS'), ('OPEN', 'OPEN'), ('NEW', 'NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('REFERRAL', 'REFERRAL')], max_length=100),
        ),
    ]
