# Generated by Django 4.0.1 on 2022-01-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_lead_lead_status_alter_lead_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('UNQUALIFIED', 'UNQUALIFIED'), ('BAD TIMING', 'BAD TIMING '), ('IN PROGRESS', 'IN PROGRESS'), ('OPEN DEAL', 'OPEN DEAL'), ('CONNECTED', 'CONNECTED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('OPEN', 'OPEN'), ('NEW', 'NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('REFERRAL', 'REFERRAL'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER')], max_length=100),
        ),
    ]
