# Generated by Django 4.0.1 on 2022-01-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('BAD TIMING', 'BAD TIMING '), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('NEW', 'NEW'), ('OPEN', 'OPEN'), ('OPEN DEAL', 'OPEN DEAL'), ('CONNECTED', 'CONNECTED'), ('UNQUALIFIED', 'UNQUALIFIED'), ('IN PROGRESS', 'IN PROGRESS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'INSTAGRAM'), ('REFERRAL', 'REFERRAL'), ('TWITTER', 'TWITTER'), ('GOOGLE SEARCH', 'GOOGLE SEARCH')], max_length=100),
        ),
    ]
