# Generated by Django 4.0.1 on 2022-01-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('OPEN', 'OPEN'), ('CONNECTED', 'CONNECTED'), ('BAD TIMING', 'BAD TIMING '), ('UNQUALIFIED', 'UNQUALIFIED'), ('IN PROGRESS', 'IN PROGRESS'), ('NEW', 'NEW'), ('OPEN DEAL', 'OPEN DEAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('REFERRAL', 'REFERRAL'), ('GOOGLE SEARCH', 'GOOGLE SEARCH'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER')], max_length=100),
        ),
    ]
