# Generated by Django 4.0.1 on 2022-01-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_lead_lead_status_alter_lead_source_of_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_contacted',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('UNQUALIFIED', 'UNQUALIFIED'), ('ATTEMPTED TO CONTACT', 'ATTEMPTED TO CONTACT'), ('OPEN DEAL', 'OPEN DEAL'), ('BAD TIMING', 'BAD TIMING '), ('IN PROGRESS', 'IN PROGRESS'), ('OPEN', 'OPEN'), ('NEW', 'NEW'), ('CONNECTED', 'CONNECTED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_of_lead',
            field=models.CharField(blank=True, choices=[('REFERRAL', 'REFERRAL'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('GOOGLE SEARCH', 'GOOGLE SEARCH')], max_length=100),
        ),
    ]
